config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update!(task_params)
    redirect_to tasks_url, notice: "タスク 「#{task.name}」を更新しました。"
  end

  def create
    task = Task.new(task_params)
    task.save!
    redirect_to tasks_url, notice: "タスク 「#{task.name}」を登録しました。"
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_url, notice: "タスク 「#{task.name}」を削除しました。"
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Taskleaf
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light 
      .navbar-brand Taskleaf
    .container
      - if flash.notice.present?
        .alert.alert-success = flash.notice
      = yield

app/views/tasks/_form.html.slim
= form_with model: task, local: true do |f|
  .form-group 
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group 
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/edit.html.slim
h1 タスクの編集

.nav.justify-content-end 
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.slim
h1 タスク一覧
= link_to '新規登録', new_task_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover 
  thead.thead-default 
    tr 
      th= Task.human_attribute_name(:name)
      th= Task.human_attribute_name(:created_at)
  tbody 
    - @tasks.each do |task|
      tr 
        td= link_to task.name, task 
        td= task.created_at
        td 
          = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
          = link_to '削除', task, method: :delete, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか？" } , class: 'btn btn-danger'

app/views/tasks/new.html.slim
h1 タスクの新規登録

.nav.justify-centent-end 
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav.justify-content-end 
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover 
  tbody 
    tr 
      th= Task.human_attribute_name(:id)
      td= @task.id
    tr 
      th= Task.human_attribute_name(:name)
      td= @task.name
    tr 
      th= Task.human_attribute_name(:description)
      td= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div")
    tr 
      th= Task.human_attribute_name(:created_at)
      td= @task.created_at  
    tr 
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at

=link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'
= link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか？" } , class: 'btn btn-danger'